services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: Adventureworks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./database/adventureworks.sql:/docker-entrypoint-initdb.d/adventureworks.sql
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d Adventureworks"]
      interval: 5s
      timeout: 5s
      retries: 10

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 5s
      timeout: 5s
      retries: 20

  ollama-model:
    image: ollama/ollama
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      OLLAMA_HOST: http://ollama:11434
    entrypoint: ["/bin/sh", "-c"]
    command: ["ollama pull nomic-embed-text"]
    volumes:
      - ollama_data:/root/.ollama
    restart: "no"

  app:
    build: .
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: Adventureworks
      DB_USER: postgres
      DB_PASSWORD: postgres
      OLLAMA_BASE_URL: http://ollama:11434
    depends_on:
      postgres:
        condition: service_healthy
      ollama-model:
        condition: service_completed_successfully

volumes:
  postgres_data:
  ollama_data: