from ..agent_state import AgentState
from ..llm import get_llm

import sqlglot
from sqlglot import exp

# uses sqlglot library which parses the sql to check if the syntax is correct 
def check_sql_syntax(sql:str) -> bool:
    try:
        sqlglot.parse_one(sql,dialect="postgres")
        return True
    except sqlglot.errors.ParseError:
        return False

# uses exp from sqlglot to check if the query is a SELECT or WITH query (read-only) - for safety 
def check_read_only(sql:str) -> bool:
    try:
        parsed = sqlglot.parse_one(sql, dialect="postgres")

        #Allow SELECT queries
        if isinstance(parsed, exp.Select):
            return True

        #Allow WITH... SELECT queries
        if isinstance(parsed, exp.With):
            return True

        return False

    except sqlglot.errors.ParseError:
        return False

def validate_sql(state: AgentState) -> AgentState:
    """This node validates the SQL that was generated by the LLM"""

    syntax_valid = check_sql_syntax(state["generated_sql"])
    read_only = check_read_only(state["generated_sql"])

    if not syntax_valid: 
        state["sql_valid"] = False

    if not read_only:
        state["sql_valid"] = False

    is_valid_sql_prompt = f'''
        Determine whether this SQL correctly answers the user's question.

        User question: {state["user_query"]}
        Business context: {state["doc_info"]}
        Database schema: {state["schema_info"]}
        Generated SQL: {state["generated_sql"]}

        Check:
            1. Does it answer the question?
            2. Does it use the correct tables and columns?
            3. Does it follow the business definitions?
            4. Are the calculations correct?

        Return only: VALID or INVALID
    '''

    llm = get_llm()
    response = llm.invoke(is_valid_sql_prompt).content.strip()

    if response == "VALID":
        state["sql_valid"] = True
    else:
        state["sql_valid"] = False

    return state